# .deepsource.toml

version = 1

exclude_patterns = [
    "bin/**",
    "tests/**",
    "k6/**",
    "kube/**",
    "vendor/**",
    "*.gen.go",  # Fichiers générés
    "**/migration/**", # Scripts de migration SQL
    "docker-compose*.yaml", # Fichiers docker-compose
    "*.js",  # Fichiers JavaScript
    "*.json",  # Fichiers JSON
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  # Indiquez le chemin de la racine du code Go
  import_path = "github.com/goodfoodcesi/auth-api"

  [analyzers.configs]
  # Active ou désactive les règles spécifiques
  gosec = true   # Analyse de sécurité
  stylecheck = true  # Vérifications de style
