services:
    goodfood-rabbitmq:
      container_name: goodfood-rabbitmq
      image: rabbitmq:3-management
      ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
    external: true
    name: goodfood-api