services:
  authapi:
    build: .
    expose:
      - "8080"
    environment:
      - Env=dev
      - APIPort=:8080
      - DBHost=ip
      - APISecret=your-super-secret-jwt-token-with-at-least-32-characters-long
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`api.goodfood.dev`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.docker.network=goodfood-api"


networks:
  default:
    external:
      name: goodfood-api